### PR TITLE
feat: Add domain update and setdefault commands

### PR DESCRIPTION
**Pull request by conor-ward**
## Proposed Changes
  - Adds `domain:update` and `domain:setdefault` commands.
  - Extract `updateVisibility` to `UpdateCommand` class.
  - Add tests for update and setdefault.
  - Change `publish` flag to `published=publish|unpublish` to allow unpublishing on update.

### CODE REVIEW

**Review by ben-smartbear — APPROVED** [review]
nice job

**Comment by barryadk** [comment]
One change that's been planned is to change the `--publish` flag on the 'update' command. Currently it's not possible to unpublish as part of the update.
The proposed flag is `--published=publish|unpublish`, this would be for api:update and domain:update.

**Review by barryadk — APPROVED** [review]
This is great. We just need to make it clear that there's a breaking change in the release notes.

**Comment by conor-ward** [comment]
> This is great. We just need to make it clear that there's a breaking change in the release notes.

Yeah I'll definitely add a bullet point on that.

**Pull request merged**
